//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIKI_ReturnSaiyans {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class config : global::System.Configuration.ApplicationSettingsBase {
        
        private static config defaultInstance = ((config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new config())));
        
        public static config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKcuraMagia {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKcuraMagia"]));
            }
            set {
                this["HTKcuraMagia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKcuraVidaSenzu {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKcuraVidaSenzu"]));
            }
            set {
                this["HTKcuraVidaSenzu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKcuraKISenzu {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKcuraKISenzu"]));
            }
            set {
                this["HTKcuraKISenzu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKtreino1 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKtreino1"]));
            }
            set {
                this["HTKtreino1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKtreino2 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKtreino2"]));
            }
            set {
                this["HTKtreino2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKtreino3 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKtreino3"]));
            }
            set {
                this["HTKtreino3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKcomerFood {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKcomerFood"]));
            }
            set {
                this["HTKcomerFood"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKatacar {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKatacar"]));
            }
            set {
                this["HTKatacar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKtreino4 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKtreino4"]));
            }
            set {
                this["HTKtreino4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKtreino5 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKtreino5"]));
            }
            set {
                this["HTKtreino5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKpausarBOT {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKpausarBOT"]));
            }
            set {
                this["HTKpausarBOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys HTKativarBOT {
            get {
                return ((global::System.Windows.Forms.Keys)(this["HTKativarBOT"]));
            }
            set {
                this["HTKativarBOT"] = value;
            }
        }
    }
}
